import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/auth";
import Nav from "./components/nav";
import Container from "./components/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Text.fy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} bg-container text-black`}>
        <AuthProvider>
          <Container>
            <div className="justify-end md:flex md:p-5 xl:w-full">
              <Nav />
            </div>

            <div className="h-full w-full overflow-auto border-solid border-gray-400 pb-20 md:border-l md:pb-5 xl:min-w-[600px] xl:max-w-[600px] xl:border-x [&::-webkit-scrollbar]:hidden">
              {children}
            </div>

            <div className="hidden w-full justify-start p-2.5 xl:flex"></div>
          </Container>
        </AuthProvider>
      </body>
    </html>
  );
}
